package org.simplemodeling.textus.cbdsupport.runtime

/*
 * @since   Jul. 16, 2026
 * @version Jul. 25, 2026
 * @author  ASAMI, Tomoharu
 */
final case class CarReviewCapabilityDefinition(
  id: ReviewCapabilityId,
  views: Vector[String],
  assessmentFocus: String,
  representativeEvidenceKinds: Vector[String],
  runtimeEvidenceRequired: Boolean
)

final case class CarReviewCapabilityProjection(
  capability: CarReviewCapabilityDefinition,
  evidenceIds: Vector[ReviewEvidenceId],
  observationIds: Vector[ReviewObservationId]
)

/** CBD-owned reusable capability definitions; projection only consumes canonical Report references. */
object CarReviewCapabilityCatalog {
  private val _definitions = Vector(
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.boundary"), Vector("security"), "Declared boundary and admission controls protect review targets and exposed operations.", Vector("security-policy", "configuration"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.authentication"), Vector("security"), "Authentication verifies workload, service, and user identities through an explicit trust boundary with credential lifecycle and failure evidence.", Vector("authentication-policy", "identity-provider", "authentication-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.authorization"), Vector("security"), "Authorization derives and enforces resource and operation access from authenticated subject context with deny-by-default and attributable decisions.", Vector("authorization-policy", "capability-contract", "authorization-decision"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.auditability"), Vector("security", "observability"), "Security-relevant actions and decisions produce tamper-resistant, attributable, bounded audit evidence with an explicit retention and access policy.", Vector("audit-policy", "audit-record", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.domain.bounded-text-datatype"), Vector("security", "domain"), "Domain object text attributes use purpose-specific bounded datatypes instead of raw strings so oversized input cannot become unbounded memory, storage, logging, or processing work.", Vector("cml-model", "datatype-contract", "validation"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.domain.constrained-numeric-datatype"), Vector("security", "domain"), "Domain object numeric attributes use purpose-specific constrained datatypes instead of raw integer or decimal primitives so negative, overflowing, or out-of-range values cannot violate domain invariants.", Vector("cml-model", "datatype-contract", "validation"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.infrastructure.immutable"), Vector("security", "resilience", "infrastructure"), "Runtime infrastructure is replaced from a declared image or artifact rather than mutated in place, with drift detection and reproducible rollout evidence.", Vector("deployment-manifest", "artifact-digest", "infrastructure-policy"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.infrastructure.non-persistent"), Vector("security", "resilience", "infrastructure"), "Compute instances retain no authoritative local state across replacement; required persistence is externalized through declared state boundaries.", Vector("deployment-manifest", "state-boundary", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.infrastructure.disposable"), Vector("security", "resilience", "infrastructure"), "Instances can be terminated and recreated through a bounded, tested procedure without losing authoritative state or bypassing recovery controls.", Vector("replacement-test", "deployment-event", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.infrastructure.volatility"), Vector("security", "resilience", "infrastructure"), "Deliberate infrastructure volatility reduces attacker dwell time and stale mutable state while preserving service identity, state, and audit continuity.", Vector("rotation-policy", "replacement-event", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.cyber-resilience"), Vector("security", "resilience"), "The component can anticipate, withstand, recover from, and adapt to adverse cyber conditions with attributable continuity and recovery evidence.", Vector("resilience-policy", "recovery-test", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.moving-target-defense"), Vector("security", "resilience", "infrastructure"), "Moving Target Defense deliberately changes an admitted attack surface or runtime characteristic under policy without breaking identity, authorization, observability, or recovery guarantees.", Vector("mtd-policy", "rotation-event", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.domain.identity-consistency"), Vector("domain", "implementation"), "Domain identifiers and relations remain consistent across model, implementation, and CAR boundaries.", Vector("cml-model", "abi"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.documentation.rationale"), Vector("documentation", "implementation"), "Public documentation explains the implemented component and operation rationale.", Vector("documentation", "cml-model"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai-readiness"), Vector("ai-readiness"), "Structured, bounded evidence is suitable for explicit opt-in AI review without provider fallback.", Vector("provider-descriptor", "evidence-bundle"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.resilience"), Vector("resilience"), "Failure, cancellation, timeout, and limitation behavior is explicit and attributable.", Vector("test-result", "execution-fact"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.testability"), Vector("testability"), "Executable tests cover the admitted component behavior and declared contracts.", Vector("test-result", "build"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.evaluability.corpus-first-experiment"), Vector("evaluability", "testability", "observability"), "Versioned evaluation corpus and experiment identities are fixed before execution, and runtime observations can be correlated to their corpus case and experiment run without reconstructing inputs from telemetry.", Vector("evaluation-corpus", "experiment-definition", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.observability.runtime-evidence"), Vector("observability", "runtime"), "Accepted runtime observations establish operational behavior beyond static analysis.", Vector("runtime-observation", "execution-fact"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.performance.latency"), Vector("performance", "runtime"), "Request and operation latency is bounded, measured, and attributable to an admitted workload.", Vector("performance-test", "latency-metric"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.performance.throughput"), Vector("performance", "runtime"), "Sustainable throughput and saturation behavior are measured for an admitted workload.", Vector("performance-test", "throughput-metric"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.performance.concurrency"), Vector("performance", "runtime"), "Concurrent execution limits, isolation, and contention behavior are explicit and verified.", Vector("concurrency-test", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.performance.resource-efficiency"), Vector("performance", "runtime", "cost-efficiency"), "CPU, memory, and I/O use is measured against useful work and declared limits.", Vector("resource-metric", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.confidentiality"), Vector("security", "runtime"), "Sensitive information is classified and protected in transit, at rest, in diagnostics, and across provider boundaries.", Vector("data-classification", "encryption-policy", "redaction-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.integrity"), Vector("security", "runtime"), "Data, artifacts, messages, and decisions retain verifiable integrity across storage and execution boundaries.", Vector("integrity-policy", "artifact-digest", "integrity-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.availability.uptime"), Vector("availability", "runtime"), "Service uptime objectives, measurement windows, and admitted exclusions are explicit.", Vector("service-level-objective", "availability-metric"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.availability.failover"), Vector("availability", "runtime", "resilience"), "Failover behavior is bounded, tested, and preserves required identity and state semantics.", Vector("failover-test", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.availability.redundancy"), Vector("availability", "runtime"), "Redundancy removes declared single points of failure without creating hidden consistency hazards.", Vector("deployment-manifest", "failure-domain"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.availability.recovery-time"), Vector("availability", "runtime", "resilience"), "Failure and repair evidence supports attributable MTBF and MTTR or equivalent recovery objectives.", Vector("incident-record", "recovery-metric"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.reliability.failure-rate"), Vector("reliability", "runtime"), "Failure frequency is measured against a declared workload and observation window.", Vector("failure-metric", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.reliability.correctness"), Vector("reliability", "runtime", "domain"), "Runtime outcomes satisfy declared domain and protocol contracts under normal and failure conditions.", Vector("executable-specification", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.reliability.data-consistency"), Vector("reliability", "runtime", "domain"), "Data consistency boundaries, conflict behavior, and recovery semantics are explicit and verified.", Vector("consistency-policy", "transaction-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.reliability.rest-request-idempotency"), Vector("reliability", "resilience", "interoperability", "security", "observability"), "REST mutation routes prevent duplicate execution through principal-scoped idempotency keys, normalized request fingerprints, in-progress coordination, bounded result replay, expiry, and conflicting-key rejection.", Vector("api-contract", "idempotency-policy", "concurrency-test", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.reliability.web-form-submission-idempotency"), Vector("reliability", "resilience", "ux", "web", "security", "observability"), "Web Form mutation routes prevent duplicate submission through principal/session-scoped one-time tokens, Post/Redirect/Get, bounded result or redirect replay, expiry, and conflicting-token rejection.", Vector("web-form-contract", "idempotency-policy", "interaction-test", "concurrency-test", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.scalability.scale-up"), Vector("scalability", "runtime"), "Vertical scaling behavior and resource ceilings are measured and documented.", Vector("scaling-test", "resource-metric"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.scalability.scale-out"), Vector("scalability", "runtime"), "Horizontal scaling preserves identity, state, ordering, and authorization semantics.", Vector("scaling-test", "deployment-event"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.scalability.elasticity"), Vector("scalability", "runtime"), "Elastic capacity changes respond to bounded signals without instability or semantic degradation.", Vector("autoscaling-policy", "scaling-event"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.resilience.retry"), Vector("resilience", "runtime"), "Retry policy is bounded, attributable, idempotency-aware, and does not amplify failure.", Vector("retry-policy", "failure-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.resilience.circuit-breaker"), Vector("resilience", "runtime"), "Circuit breaking has explicit thresholds, states, recovery, and diagnostics.", Vector("circuit-breaker-policy", "failure-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.resilience.bulkhead"), Vector("resilience", "runtime"), "Resource and failure isolation prevents one workload or dependency from exhausting unrelated work.", Vector("isolation-policy", "load-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.resilience.self-healing"), Vector("resilience", "runtime"), "Automated recovery is bounded, observable, and proven not to hide persistent faults.", Vector("recovery-policy", "recovery-event"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.operability.logging"), Vector("operability", "operational"), "Operators receive bounded and actionable logs without sensitive payload leakage.", Vector("logging-policy", "log-sample"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.operability.tracing"), Vector("operability", "operational", "observability"), "Execution traces preserve causal structure and stable correlation across component boundaries.", Vector("trace-contract", "runtime-trace"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.operability.metrics"), Vector("operability", "operational", "observability"), "Metrics have stable semantics, bounded cardinality, and operationally useful labels.", Vector("metric-contract", "runtime-metric"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.operability.admin-api"), Vector("operability", "operational"), "Administrative operations are discoverable, authorized, bounded, and diagnostically useful.", Vector("admin-api", "authorization-policy"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.observability.structured-logging"), Vector("observability", "operational"), "Logs use structured, stable fields that retain severity, identity, correlation, and diagnostic meaning.", Vector("logging-schema", "log-sample"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.observability.distributed-tracing"), Vector("observability", "operational"), "Distributed traces preserve context, causation, sampling limits, and provider attribution.", Vector("trace-contract", "distributed-trace"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.observability.metrics-visualization"), Vector("observability", "operational"), "Metrics can be interpreted through a documented dashboard or equivalent projection without hidden calculations.", Vector("metric-contract", "dashboard-projection"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.observability.state-visibility"), Vector("observability", "operational"), "Relevant runtime, Job, Task, provider, and resource states are visible with explicit staleness and authority.", Vector("state-projection", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.deployability.rollback"), Vector("deployability", "operational"), "Rollback is defined, bounded, and tested together with schema and state compatibility.", Vector("deployment-policy", "rollback-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.deployability.blue-green"), Vector("deployability", "operational"), "Blue/Green deployment has explicit traffic, state, compatibility, and rollback semantics.", Vector("deployment-policy", "deployment-event"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.deployability.canary"), Vector("deployability", "operational"), "Canary deployment uses bounded admission, comparison, abort, and promotion evidence.", Vector("deployment-policy", "evaluation-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.configurability.external-configuration"), Vector("configurability", "operational"), "Configuration is externalized through typed, validated, attributable sources rather than hidden constants.", Vector("configuration-schema", "configuration-source"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.configurability.dynamic-change"), Vector("configurability", "operational"), "Dynamic configuration changes define admission, consistency, rollback, and audit semantics.", Vector("configuration-policy", "configuration-event"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.configurability.feature-toggle"), Vector("configurability", "operational"), "Feature toggles are typed, scoped, observable, lifecycle-managed, and fail safely.", Vector("feature-toggle-policy", "configuration-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.maintainability.modifiability"), Vector("maintainability", "design-time"), "Expected changes can be made through explicit extension points with bounded regression scope.", Vector("architecture", "change-history"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.maintainability.understandability"), Vector("maintainability", "design-time", "readability"), "Responsibilities, boundaries, and behavior are understandable from model, code, and documentation.", Vector("architecture", "documentation"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.maintainability.local-change"), Vector("maintainability", "design-time"), "A local requirement change remains localized rather than propagating through unrelated modules.", Vector("dependency-graph", "change-history"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.extensibility.plugin-structure"), Vector("extensibility", "design-time"), "Plugin extension points are explicit, versioned, isolated, and lifecycle-managed.", Vector("plugin-contract", "extension-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.extensibility.spi-design"), Vector("extensibility", "design-time"), "SPI contracts separate provider-neutral semantics from replaceable implementations with deterministic compatibility.", Vector("spi-contract", "provider-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.extensibility.api-stability"), Vector("extensibility", "design-time", "evolvability"), "Public APIs have explicit compatibility, versioning, and removal policy.", Vector("api-contract", "abi-report"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.reusability.component-independence"), Vector("reusability", "design-time"), "The component owns a coherent contract and avoids application-specific or provider-specific coupling.", Vector("dependency-graph", "component-contract"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.reusability.generality"), Vector("reusability", "design-time"), "Reusable abstractions express demonstrated common semantics without erasing required domain distinctions.", Vector("component-contract", "usage-example"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.testability.mockability"), Vector("testability", "design-time"), "External effects can be replaced by bounded deterministic test providers without changing business semantics.", Vector("test-fixture", "provider-contract"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.testability.isolation"), Vector("testability", "design-time"), "Behavior can be exercised with explicit dependencies and controlled state boundaries.", Vector("test-architecture", "executable-specification"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.testability.deterministic-execution"), Vector("testability", "design-time", "evaluability"), "Equivalent admitted inputs and execution context produce reproducible decisions and evidence.", Vector("determinism-contract", "executable-specification"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.readability.naming"), Vector("readability", "design-time"), "Names consistently express domain and framework concepts without hidden aliases or ambiguous abbreviations.", Vector("naming-rule", "source-analysis"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.readability.dsl-expressiveness"), Vector("readability", "design-time", "ai-readiness"), "DSL constructs express intent and constraints directly without requiring implementation inference.", Vector("dsl-model", "language-specification"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.readability.documentation-linkage"), Vector("readability", "design-time", "documentation"), "Rules, specifications, design, implementation, and executable evidence remain navigably linked.", Vector("documentation-map", "executable-coverage"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.consistency.model"), Vector("consistency", "design-time", "domain"), "Domain, protocol, storage, and projection models preserve one declared semantic contract.", Vector("model-contract", "projection-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.consistency.api"), Vector("consistency", "design-time"), "Related APIs use consistent naming, envelopes, lifecycle, authorization, and error semantics.", Vector("api-contract", "schema-projection"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.consistency.error-model"), Vector("consistency", "design-time"), "Failures use one structured error model across execution, transport, observability, and user surfaces.", Vector("error-contract", "failure-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.portability.environment-dependency"), Vector("portability", "business"), "Environment dependencies are declared, bounded, and replaceable rather than inferred from an ambient host.", Vector("dependency-manifest", "configuration-schema"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.portability.container-fitness"), Vector("portability", "business", "deployability"), "The component supports container lifecycle, configuration, resource, signal, and state boundaries.", Vector("container-manifest", "container-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.portability.cloud-independence"), Vector("portability", "business"), "Cloud-specific implementation remains behind explicit provider contracts with a viable portable core.", Vector("provider-contract", "dependency-graph"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.interoperability.api-protocol"), Vector("interoperability", "business"), "OpenAPI, gRPC, or equivalent API projections retain the canonical operation contract.", Vector("openapi", "protocol-schema"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.interoperability.standard-protocol"), Vector("interoperability", "business"), "External protocols follow admitted standards and make extensions and compatibility explicit.", Vector("protocol-specification", "compatibility-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.evolvability.versioning"), Vector("evolvability", "business"), "Artifacts, APIs, schemas, and providers have an explicit coordinated versioning strategy.", Vector("version-policy", "artifact-metadata"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.evolvability.backward-compatibility"), Vector("evolvability", "business"), "Compatibility promises are executable, scoped, and distinguished from intentional breaking changes.", Vector("compatibility-policy", "abi-report"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.evolvability.migration"), Vector("evolvability", "business"), "State, configuration, API, and deployment migrations have bounded, reversible procedures and evidence.", Vector("migration-plan", "migration-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.cost-efficiency.infrastructure"), Vector("cost-efficiency", "business"), "Infrastructure cost drivers are attributable to measured capacity, utilization, and service objectives.", Vector("resource-metric", "cost-record"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.cost-efficiency.operations"), Vector("cost-efficiency", "business", "operability"), "Operational effort and continuing service cost are attributable without hiding quality trade-offs.", Vector("operation-record", "cost-record"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.cost-efficiency.development"), Vector("cost-efficiency", "business"), "Development and maintenance efficiency is supported by bounded workflow evidence rather than unsupported productivity claims.", Vector("workflow-evidence", "change-history"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.model-interpretability.dsl-structure"), Vector("ai-readiness", "model-interpretability"), "DSL structure exposes typed intent, relationships, and constraints for bounded AI interpretation.", Vector("dsl-model", "language-specification"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.model-interpretability.structured-natural-language"), Vector("ai-readiness", "model-interpretability"), "Structured natural-language descriptions remain linked to canonical model identities and constraints.", Vector("documentation", "model-contract"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.operability.mcp"), Vector("ai-readiness", "ai-operability"), "MCP publication is bounded, authorized, described, versioned, and aligned with canonical operations.", Vector("mcp-catalog", "authorization-policy"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.operability.skill"), Vector("ai-readiness", "ai-operability", "skill"), "Skill publication is bounded, versioned, task-accurate, authority-aware, and aligned with canonical component operations and MCP guidance.", Vector("skill-bundle", "skill-manifest", "skill-validation"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.operability.spec-componentization"), Vector("ai-readiness", "ai-operability"), "Specifications are componentized and discoverable as stable task and contract context.", Vector("specification", "component-contract"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.operability.automatic-tooling"), Vector("ai-readiness", "ai-operability"), "Tool projection is deterministic, bounded, and safe rather than inferred from arbitrary implementation methods.", Vector("tool-catalog", "schema-projection"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.context-stability.phase-structure"), Vector("ai-readiness", "context-stability"), "Development phase state and completion evidence provide stable bounded context for AI-assisted work.", Vector("phase-document", "executable-coverage"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.context-stability.responsibility-boundary"), Vector("ai-readiness", "context-stability"), "Component, provider, framework, and application responsibilities are explicit and stable.", Vector("architecture", "dependency-graph"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.generatability.dsl-clarity"), Vector("ai-readiness", "generatability"), "DSL generation rules are explicit enough to avoid implementation-specific guesswork.", Vector("language-specification", "generation-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.generatability.determinism"), Vector("ai-readiness", "generatability", "testability"), "Equivalent model input produces deterministic generated contracts and artifacts.", Vector("generation-test", "artifact-digest"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai.generatability.syntax-constraints"), Vector("ai-readiness", "generatability"), "Syntax constraints and invalid forms are explicit, machine-checkable, and diagnostically useful.", Vector("language-schema", "validation-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ux.web"), Vector("ux", "web"), "Web surfaces make principal user tasks discoverable, understandable, operable, and recoverable with accessible feedback.", Vector("web-surface", "web-interaction", "web-accessibility"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ux.cli"), Vector("ux", "cli"), "CLI surfaces provide discoverable commands, stable inputs and outputs, actionable diagnostics, and automation-safe behavior.", Vector("cli-surface", "cli-interaction", "command-help"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ux.skill-assisted"), Vector("ux", "skill", "ai-readiness"), "Component Skills provide accurate task guidance, prerequisites, limitations, safe authority boundaries, and recovery procedures.", Vector("skill-bundle", "skill-manifest", "skill-validation"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ux.cross-surface-consistency"), Vector("ux", "web", "cli", "skill"), "Web, CLI, and Skill-assisted surfaces use consistent task vocabulary, operation semantics, results, and diagnostics.", Vector("surface-contract", "operation-contract", "documentation"), runtimeEvidenceRequired = false)
  )

  private val _additional_definitions = Vector(
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.functional-suitability.completeness"), Vector("functional-suitability"), "Functions cover the declared user and domain tasks without material omissions.", Vector("requirements-trace", "executable-specification"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.functional-suitability.correctness"), Vector("functional-suitability", "reliability"), "Functions produce correct results with the required precision for admitted inputs.", Vector("domain-contract", "executable-specification"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.functional-suitability.appropriateness"), Vector("functional-suitability", "ux"), "Functions facilitate the declared task rather than forcing unnecessary or misleading work.", Vector("use-case", "interaction-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.accessibility.perceivable"), Vector("accessibility", "ux"), "Information and controls are available through perceivable alternatives for supported users and assistive technologies.", Vector("accessibility-test", "rendered-surface"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.accessibility.operable"), Vector("accessibility", "ux"), "Supported interactions are operable by keyboard and assistive input without traps or inaccessible timing assumptions.", Vector("accessibility-test", "interaction-trace"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.accessibility.understandable"), Vector("accessibility", "ux"), "Content, navigation, input expectations, and errors are understandable and predictable.", Vector("content-review", "interaction-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.accessibility.robust"), Vector("accessibility", "ux", "interoperability"), "Semantic output remains compatible with supported user agents and assistive technologies.", Vector("markup-validation", "assistive-technology-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.supply-chain.artifact-provenance"), Vector("supply-chain", "security"), "Released artifacts retain verifiable source, build, signer, and distribution provenance.", Vector("attestation", "artifact-signature"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.supply-chain.dependency-governance"), Vector("supply-chain", "security"), "Dependencies are admitted through explicit version, origin, license, and trust policy.", Vector("dependency-lock", "admission-policy"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.supply-chain.reproducible-build"), Vector("supply-chain", "security", "testability"), "Equivalent admitted sources and toolchains can reproduce artifact identity or explain bounded differences.", Vector("build-attestation", "artifact-digest"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.supply-chain.vulnerability-response"), Vector("supply-chain", "security", "operability"), "Known component vulnerabilities have attributable triage, remediation, exception, and release procedures.", Vector("vulnerability-report", "remediation-record"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.security.supply-chain.sbom-completeness"), Vector("supply-chain", "security"), "The software bill of materials covers distributed runtime and build-relevant components with stable identities.", Vector("sbom", "artifact-manifest"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.privacy.data-minimization"), Vector("privacy", "security", "governance"), "Collection, transfer, retention, and exposure are limited to data necessary for a declared purpose.", Vector("data-inventory", "privacy-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.privacy.purpose-limitation"), Vector("privacy", "governance"), "Personal or sensitive data use remains bound to declared purposes and authorized processing contexts.", Vector("purpose-policy", "processing-record"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.privacy.retention-deletion"), Vector("privacy", "governance", "operability"), "Retention, expiry, deletion, and legal-hold semantics are explicit, attributable, and testable.", Vector("retention-policy", "deletion-audit"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.privacy.consent-user-agency"), Vector("privacy", "ux", "governance"), "Required consent and user choices are informed, revocable, and enforced across relevant processing.", Vector("consent-policy", "user-choice-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.privacy.sensitive-data-disclosure"), Vector("privacy", "security", "observability"), "Sensitive data disclosure is prevented or explicitly authorized across APIs, logs, traces, reports, and providers.", Vector("redaction-test", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.safety.hazard-identification"), Vector("safety", "governance"), "Foreseeable harmful states, affected parties, triggers, and controls are identified for the admitted scope.", Vector("hazard-analysis", "risk-register"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.safety.fail-safe-behavior"), Vector("safety", "resilience"), "Failures move the system to a bounded state that does not create avoidable harm.", Vector("failure-policy", "fault-injection-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.safety.human-override"), Vector("safety", "ux", "operability"), "Authorized humans can understand, interrupt, or override safety-relevant automated behavior where required.", Vector("override-policy", "operator-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.safety.safe-degradation"), Vector("safety", "resilience", "availability"), "Degraded operation preserves explicit safety invariants and communicates lost capability.", Vector("degradation-policy", "failure-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.safety.blast-radius-containment"), Vector("safety", "resilience", "security"), "Faults, misuse, and harmful actions are contained within declared resource, tenant, and operation boundaries.", Vector("isolation-policy", "containment-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.data-quality.accuracy"), Vector("data-quality", "domain"), "Data values correctly represent the admitted real-world or domain facts within declared tolerance.", Vector("validation-rule", "reference-comparison"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.data-quality.completeness"), Vector("data-quality", "domain"), "Required records, fields, relations, and temporal coverage are present for the declared use.", Vector("schema-profile", "completeness-report"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.data-quality.currentness"), Vector("data-quality", "reliability"), "Data freshness, effective time, expiry, and staleness are explicit for the declared use.", Vector("freshness-policy", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.data-quality.credibility"), Vector("data-quality", "governance"), "Data claims retain attributable source authority, confidence, and contestability.", Vector("source-provenance", "authority-policy"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.data-quality.lineage"), Vector("data-quality", "observability", "governance"), "Derivation, transformation, source, and publication lineage remain traceable across data boundaries.", Vector("lineage-record", "provenance-graph"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.data-quality.semantic-consistency"), Vector("data-quality", "domain", "consistency"), "Equivalent concepts, identifiers, units, and relations retain one declared meaning across representations.", Vector("semantic-model", "consistency-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai-trustworthiness.valid-reliable"), Vector("ai-trustworthiness", "ai-readiness", "reliability"), "AI behavior is valid and reliable for a declared purpose, population, context, and evaluation boundary.", Vector("evaluation-corpus", "experiment-result"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai-trustworthiness.safe"), Vector("ai-trustworthiness", "ai-readiness", "safety"), "AI use identifies and controls foreseeable harmful outcomes with bounded fallback and human authority.", Vector("ai-risk-assessment", "safety-evaluation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai-trustworthiness.secure-resilient"), Vector("ai-trustworthiness", "ai-readiness", "security", "resilience"), "AI inputs, models, tools, context, and outputs resist admitted attacks and recover from failure.", Vector("threat-model", "adversarial-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai-trustworthiness.accountable-transparent"), Vector("ai-trustworthiness", "ai-readiness", "governance"), "AI ownership, purpose, provider, model, policy, evidence, and consequential decisions are attributable and transparent.", Vector("model-card", "decision-record"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai-trustworthiness.explainable-interpretable"), Vector("ai-trustworthiness", "ai-readiness"), "Relevant AI outputs and limitations can be interpreted and explained at the level required by affected users and operators.", Vector("explanation-contract", "user-evaluation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai-trustworthiness.privacy-enhanced"), Vector("ai-trustworthiness", "ai-readiness", "privacy"), "AI data, context, prompts, training, retention, and provider exchange apply declared privacy-enhancing controls.", Vector("privacy-policy", "provider-evidence"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.ai-trustworthiness.fairness-harmful-bias"), Vector("ai-trustworthiness", "ai-readiness", "safety"), "Relevant harmful bias and fairness risks are measured, bounded, monitored, and governed for the admitted context.", Vector("fairness-evaluation", "monitoring-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.compatibility.runtime-coexistence"), Vector("compatibility", "interoperability"), "The component coexists with declared runtime peers without semantic or lifecycle interference.", Vector("integration-test", "runtime-observation"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.compatibility.resource-coexistence"), Vector("compatibility", "performance"), "Shared CPU, memory, I/O, network, and storage use remains within declared isolation and fairness limits.", Vector("resource-policy", "contention-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.compatibility.dependency-compatibility"), Vector("compatibility", "evolvability"), "Dependency and platform version ranges are explicit and verified without accidental classpath or ABI coupling.", Vector("compatibility-matrix", "abi-report"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.business-continuity.backup-recoverability"), Vector("business-continuity", "availability", "resilience"), "Authoritative state can be backed up, verified, restored, and reconciled through tested procedures.", Vector("backup-policy", "restore-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.business-continuity.recovery-point-objective"), Vector("business-continuity", "availability"), "Maximum admitted data loss is explicit and supported by measured recovery evidence.", Vector("continuity-objective", "recovery-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.business-continuity.recovery-time-objective"), Vector("business-continuity", "availability"), "Maximum admitted restoration time is explicit and supported by measured recovery evidence.", Vector("continuity-objective", "recovery-metric"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.business-continuity.regional-continuity"), Vector("business-continuity", "availability", "resilience"), "Declared regional or site loss scenarios preserve required service and state semantics.", Vector("failure-domain", "regional-recovery-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.internationalization.locale"), Vector("internationalization", "portability", "ux"), "Locale-sensitive behavior is explicit and does not depend on an ambient process locale.", Vector("locale-contract", "localization-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.internationalization.timezone"), Vector("internationalization", "portability"), "Instants, local times, zones, daylight transitions, and display policy are modeled explicitly.", Vector("time-contract", "timezone-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.internationalization.character-encoding"), Vector("internationalization", "interoperability"), "Character encoding and normalization are explicit across storage, protocol, and rendering boundaries.", Vector("encoding-contract", "roundtrip-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.internationalization.translation"), Vector("internationalization", "ux"), "User-facing messages and content have explicit translation ownership, fallback, and completeness policy.", Vector("translation-catalog", "localization-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.internationalization.cultural-format"), Vector("internationalization", "ux"), "Names, addresses, numbers, currencies, units, and calendars follow declared cultural formatting rules.", Vector("formatting-policy", "locale-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.supportability.diagnosability"), Vector("supportability", "operability", "observability"), "Operators can isolate a failure from bounded diagnostics without exposing sensitive payloads.", Vector("diagnostic-contract", "incident-exercise"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.supportability.reproducibility"), Vector("supportability", "testability"), "A reported problem can be reproduced from versioned inputs, configuration, environment, and execution identity.", Vector("reproduction-bundle", "test-result"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.supportability.repairability"), Vector("supportability", "maintainability"), "Repair, rollback, replacement, and data correction procedures are bounded and verifiable.", Vector("repair-procedure", "recovery-test"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.supportability.operator-guidance"), Vector("supportability", "operability", "ux"), "Diagnostics link operators to accurate next actions, authority requirements, and escalation paths.", Vector("runbook", "diagnostic-test"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.compliance.policy-traceability"), Vector("compliance", "governance"), "Applicable policy obligations trace to controls, implementation, Evidence, and accountable owners.", Vector("control-mapping", "evidence-index"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.compliance.evidence-retention"), Vector("compliance", "governance", "auditability"), "Required compliance Evidence has explicit retention, integrity, access, and deletion semantics.", Vector("retention-policy", "audit-record"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.compliance.exception-governance"), Vector("compliance", "governance"), "Policy exceptions are time-bounded, approved, attributable, reviewed, and prevented from becoming silent defaults.", Vector("exception-record", "approval-policy"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.compliance.regulatory-mapping"), Vector("compliance", "governance"), "Regulatory claims identify jurisdiction, scope, version, interpretation, and supporting controls without implying unsupported certification.", Vector("regulatory-profile", "control-mapping"), runtimeEvidenceRequired = false),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.sustainability.energy-efficiency"), Vector("sustainability", "cost-efficiency", "performance"), "Energy use is attributable to useful work and optimized without hiding reliability or service trade-offs.", Vector("energy-metric", "workload-profile"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.sustainability.carbon-intensity"), Vector("sustainability", "cost-efficiency"), "Carbon-impact claims state measurement scope, location/time factors, and uncertainty.", Vector("carbon-accounting", "runtime-metric"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.sustainability.hardware-efficiency"), Vector("sustainability", "performance"), "Hardware utilization, lifetime, overprovisioning, and replacement are considered against delivered service.", Vector("capacity-report", "resource-metric"), runtimeEvidenceRequired = true),
    CarReviewCapabilityDefinition(ReviewCapabilityId("quality.sustainability.work-avoidance"), Vector("sustainability", "performance", "cost-efficiency"), "Unnecessary computation, transfer, retention, polling, retries, and generation are identified and bounded.", Vector("workload-analysis", "runtime-observation"), runtimeEvidenceRequired = true)
  )

  val definitions: Vector[CarReviewCapabilityDefinition] = (_definitions ++ _additional_definitions).sortBy(_.id.value)

  val viewNames: Vector[String] = definitions.flatMap(_.views).distinct.sorted

  def capabilityIdsForView(view: String): Set[ReviewCapabilityId] =
    definitions.filter(_.views.contains(view)).map(_.id).toSet

  def definition(id: ReviewCapabilityId): Option[CarReviewCapabilityDefinition] =
    definitions.find(_.id == id)

  def project(report: CarReviewReport): Vector[CarReviewCapabilityProjection] =
    definitions.flatMap { definition =>
      val assessment = report.assessments.find(_.capabilityId == definition.id)
      val observations = report.observations.filter(_.mappings.qualityCapabilities.contains(definition.id))
      val evidenceids = (assessment.toVector.flatMap(_.evidenceIds) ++ observations.flatMap(_.evidenceIds)).distinct.sortBy(_.value)
      val observationids = (assessment.toVector.flatMap(_.observationIds) ++ observations.map(_.id)).distinct.sortBy(_.value)
      if (evidenceids.nonEmpty || observationids.nonEmpty) Some(CarReviewCapabilityProjection(definition, evidenceids, observationids)) else None
    }
}
